### 获取用户信息
POST http://localhost:6081/rpc
Content-Type: application/json

{
  "service": "cn.syx.rpc.demo.api.UserService",
  "methodSign": "findById(int)",
  "args": [10000]
}

### 通过6081调用配置项
GET http://localhost:6081/metas

### 获取用户信息
GET http://localhost:7080/find/id?id=100

### 获取用户信息-超时
GET http://localhost:7080/find/timeout?id=100&timeout=1100&fireTimeout=false

### 获取用户信息-超时
GET http://localhost:7080/find/timeout?id=100&timeout=1100&fireTimeout=true

### 测试demo
POST http://localhost:6080/
Content-Type: application/json

{
"service": "cn.syx.rpc.demo.api.DemoService",
"methodSign": "aaa(int,java.lang.String)",
"args": [1888, "hello"]
}

### 测试getUserList
POST http://localhost:6081/
Content-Type: application/json

{
  "service": "cn.syx.rpc.demo.api.UserService",
  "methodSign": "getUserList(java.util.List)",
  "args": [[{"id":1,"name":"name1"},{"id":2,"name":"name2"},{"id":3,"name":"name3"}]]
}

### 测试userListToMap
POST http://localhost:6080/
Content-Type: application/json

{
  "service": "cn.syx.rpc.demo.api.UserService",
  "methodSign": "userListToMap(java.util.List)",
  "args": [[{"id":1,"name":"name1"},{"id":2,"name":"name2"},{"id":3,"name":"name3"}]]
}

### demo测试
GET http://localhost:7080/demo?method=bbb&param=123

### demo测试
GET http://localhost:7080/demo?method=ccc&param=123

### demo测试
GET http://localhost:7080/demo?method=hhh&param=123